int maxProfit(int* prices, int pricesSize){
    // Initialize the max profit...
    int maximumProfit = 0;
    // Traverse all the element through loop...
    for (int i = 1; i < pricesSize; i++) {
        // check if the price is greater at i...
        if (prices[i] > prices[i - 1])
            // Add the difference to profit and increse it...
            maximumProfit += prices[i] - prices[i - 1];
    }
    return maximumProfit;      // Return the meximum profit...
}
